patrimony/urls.py
from django.conf.urls import url

from . import views
from .views import homePatrimony

urlpatterns = [
    url(r'^$', homePatrimony, name='index'),#pagina inicial de patrimônio

#urls de equipamentos
    url(r'^equipment/$', views.EquipmentList.as_view(), name='equipment'),#lista de equipamentos
    url(r'^equipment/create$', views.equipment_create, name='register_equipment'),#cadastrar equipamento
    url(r'^equipment/(?P<pk>\d+)/detail/$', views.DetailEquipmentView.as_view(), name='detail_equipment'),#detalhar equipamento
    url(r'^equipment/(?P<pk>\d+)/delete/$', views.equipment_delete, name='equipment_delete'),#deletar equipamento
    url(r'^equipment/(?P<pk>\d+)/update/$', views.equipment_update, name='equipment_update'),#atualizar equipamento
    url(r'^equipment/(?P<pk>\d+)/responsibility$', views.equipment_responsibility, name='equipment_responsibility'),#Termo de Responsabilidade para novos objetos
    url(r'^equipment/(?P<pk>\d+)/detail/tombo_history$', views.tombo_history, name='tombo_history'),#histórico de tombo

#urls de movimentações
    url(r'^moviment/$', views.MovimentList.as_view(), name='moviment'),#lista de movimentações
    url(r'^moviment/create$', views.moviment_create, name='moviment_create'),#requisitar movimentações
    url(r'^moviment/search$', views.SearchMoviment.as_view(), name='moviment_search'),#Pesquisar por movimentações
    url(r'^moviment/(?P<pk>\d+)/detail/$', views.moviment_detail, name='moviment_detail'),#detalhar movimentação
    url(r'^moviment/(?P<pk>\d+)/update/$', views.moviment_update, name='moviment_update'),#atualizar movimentação
    url(r'^moviment/(?P<pk>\d+)/delete/$', views.moviment_delete, name='moviment_delete'),#deletar movimentação

#urls tombos na movimentação
    url(r'^moviment/create/search_tombo(?P<pk>\d+)$', views.search_tombo_moviment, name='search_tombo'),#Pesquisar tombos para movimentação
    url(r'^moviment/(?P<pk_m>\d+)/detail/add_tombo(?P<pk_t>\d+)$', views.add_tombo_moviment, name='add_tombo'),#adicionar tombos a movimentação
    url(r'^moviment/(?P<pk_m>\d+)/detail/del_tombo(?P<pk_t>\d+)$', views.del_tombo_moviment, name='del_tombo'),#adicionar tombos a movimentação

#urls autorizar movimentações
    url(r'^moviment/(?P<pk>\d+)/authorize$', views.authorize, name='authorize'),#Autorizar movimentação
    url(r'^moviment/(?P<pk>\d+)/finish$', views.finish, name='finish'),#Finalizar movimentação
    url(r'^moviment/(?P<pk>\d+)/responsibility$', views.responsibility, name='responsibility'),#Termo de Responsabilidade da movimentação
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import home

urlpatterns = [

    url(r'^$', home, name='home'),

    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password/change/$',auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    url(r'^password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),

    url(r'^helpdesk/', include('helpdesk.urls', namespace='helpdesk')),

    url(r'^vehicle_request/', include('vehicle_request.urls', namespace='vehicle_request')),

    url(r'^patrimony/', include('patrimony.urls', namespace="patrimony")),
    
    url(r'^admin/', admin.site.urls),
]

patrimony/models.py
from django.db import models
from django.contrib.auth import get_user_model
from organization.models import Unit
from django.db.models import Q

# Create your models here.
User = get_user_model()

class State(models.Model):
    CONSERVATION_STATE = (
            (0, 'Novo'),
            (1, 'Bom'),
            (2, 'Ruim'),
            (3, 'Inservível')
        )

#########################
#Tipo de Bem Patrimonial
#########################
class EquipmentType(models.Model):
    equipment_type = models.CharField(verbose_name='tipo de bem patrimonial', max_length=100, unique=True)

    def clean(self):
        self.equipment_type = self.equipment_type.capitalize()

    def __str__(self):
        return self.equipment_type
    
    class Meta:
        permissions = (("can_access_patrimony", "pode acessar patrimonio"),
            ("can_authorize_moviment", "pode autorizar movimentacoes"),)

##########################
#Bem Patrimonial
##########################
######QuerySet######
class EquipmentQuerySet(models.query.QuerySet):
    def search(self, query):
        lookups = (
            Q(location__name__icontains=query)
        )
        return self.filter(lookups).distinct()

######Manager######
class EquipmentManager(models.Manager):
    def get_queryset(self):
        return EquipmentQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)
########Equipment##########
class Equipment(models.Model):

    equipment_type = models.ForeignKey(
        EquipmentType, related_name='equipamento', on_delete=models.SET_NULL, null=True)
    name = models.CharField('bem patrimonial', max_length=150)
    tombo = models.PositiveSmallIntegerField(null=True, blank=True, default=True)
    location = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True)
    conservation = models.IntegerField('estado de conservação', choices=State.CONSERVATION_STATE, null=False)
    description = models.TextField('descrição')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    active = models.BooleanField('ativo', default=True)

    objects = EquipmentManager()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name

###################################
#Movimentação de Patrimonio
###################################
######QuerySet######
class MovimentRequestQuerySet(models.query.QuerySet):
    def user(self, request):
        return self.filter(user=request.user)
    
    def search(self, query):
        lookups = (
            Q(pk__icontains=query) |
            Q(user__username__icontains=query) |
            Q(destiny__name__icontains=query)
        )
        return self.filter(lookups).distinct()
    
    def units(self, query):
        lookups = (
            Q(unit__pk__in=query)
        )
        return self.filter(lookups).distinct()

######Manager######
class MovimentRequestManager(models.Manager):
    def get_queryset(self):
        return MovimentRequestQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)

class MovimentRequest(models.Model):
    OPEN_STATUS = 1
    AUTHORIZED_STATUS = 2
    CLOSED_STATUS = 3

    STATUS_CHOICES = (
        (OPEN_STATUS, 'Aberto / Não Autorizado'),
        (AUTHORIZED_STATUS, 'Autorizado'),
        (CLOSED_STATUS, 'Transferido'),
    )
    user = models.ForeignKey(
        User, related_name='moviment_request', on_delete=models.SET_NULL, null=True)
    destiny = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True)
    authorized_by = models.ForeignKey(
        User, related_name='authorized_request', on_delete=models.SET_NULL, null=True)
    authorized_date = models.DateTimeField(blank=True, null=True)
    created = models .DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=OPEN_STATUS)
    obs = models.TextField(blank=True, null=True)

    objects = MovimentRequestManager()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.destiny

# ##########################################
# #Tombos na movimentações
# ##########################################
# #################
# #QuerySet
# #################
class TombosAddQuerySet(models.query.QuerySet):

    def search(self, query):
        lookups = (
            Q(tombo__icontains=query)
        )
        return self.filter(lookups).distinct()

# ################
# #Manager
# ################
class TombosAddManager(models.Manager):

    def get_queryset(self):
        return TombosAddQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)

class TombosAddMoviment(models.Model):

    moviment = models.ForeignKey(MovimentRequest, on_delete=models.SET_NULL, null=True)
    tombo = models.ForeignKey(Equipment, on_delete=models.SET_NULL, null=True)
    new_location = models.CharField(max_length=250, null=True, blank=True)
    previous_location = models.CharField(max_length=250, null=True, blank=True)
    date_moviment = models.DateTimeField(null=True)
    previous_conservation = models.IntegerField(choices=State.CONSERVATION_STATE, null=True)
    new_conservation = models.IntegerField(choices=State.CONSERVATION_STATE, null=False)


    objects = TombosAddManager()

    def __int__(self):
        return self.tombo

patrimony/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models

#######Form para tipo de equipamento############
class TypeEquipmentForm(forms.ModelForm):
    class Meta:
        model = models.EquipmentType
        fields = ['equipment_type']
        labels = {
            'equipment_type': ('Tipo de Bem Patrimonial'),
        }

######Form para equipamentos#################
class EquipmentForm(forms.ModelForm):
    class Meta:
        model = models.Equipment
        fields = ['equipment_type', 'name', 'tombo', 'location', 'conservation', 'description']
        labels = {
            'equipment_type':'Tipo de Bem Patrimonial',
            'name':'Marca do Bem Patrimonial',
            'tombo':'Tombo',
            'location':'Localização',
            'conservation':'Estado de Conservação',
            'description':'Descrição',
        }

        widgets = {'description': forms.Textarea(attrs={'rows': '3'})}

class EquipmentEditForm(forms.ModelForm):
    class Meta:
        model = models.Equipment
        fields = ['equipment_type', 'name', 'description']
        labels = {
            'equipment_type':'Tipo de Bem Patrimonial',
            'name':'Marca do Bem Patrimonial',
            'description':'Descrição',
        }

        widgets = {'description': forms.Textarea(attrs={'rows':'3'})}

#######Form para movimentação de patrimônio#########
class MovimentRequestForm(forms.ModelForm):
    class Meta:
        model = models.MovimentRequest
        fields = ['destiny', 'obs']
        
        labels = {
            'destiny': ('Destino'),
            'obs': ('Observação'),
        }

        widgets = { 'obs': forms.Textarea(attrs={'rows': '3'}), }

class SearchTombosForm(forms.ModelForm):
    # location = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Localização'}))
    class Meta:
        model = models.Equipment
        fields = ['equipment_type', 'location']
        labels = {'equipment_type':'Tipo', 'location':'Localização'}
        # widgets = {'model': forms.TextInput(attrs={'mr': '3'}),}
    def __init__(self, *args, **kwargs):
        super(SearchTombosForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = False

class AddTombosForm(forms.ModelForm):
    class Meta:
        model = models.TombosAddMoviment
        fields = ['moviment', 'tombo']

patrimony/templates/patrimony/moviment/moviment_create.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}
    <script src="{% static 'patrimony/js/moviments.js' %}"></script>
{% endblock %}

{% block title %} Solicitar Movimentação {% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:index' %}">Patrimônio</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:moviment' %}">Movimentações</a></li>
    <li class="breadcrumb-item active">Solicitar Movimentação</li>
{% endblock %}

{% block content %}
    <div>
        <h5 class="mb-4">Solicitação de Movimentação</h5>
        <form action="{% url 'patrimony:moviment_create' %}" method="post">
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button class="btn btn-success mb-3" type="submit">Cadastrar</button>
        </form>
{% endblock %}

patrimony/templates/patrimony/moviment/moviment_delete.html
{% load widget_tweaks %}

<form method="post" action="{% url 'patrimony:moviment_delete' moviment.pk %}" class="js-moviment-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Deletar Movimentação</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Você tem certeza que deseja deletar a movimentação de <strong>{{ moviment.user }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-danger">Excluir</button>
  </div>
</form>

patrimony/templates/patrimony/moviment/moviment_detail.html
{% extends 'base.html' %}
{% load moviment_extras %}
{% load static %}
{% block javascript %}
  <script src="{% static 'patrimony/js/moviments.js' %}"></script>
{% endblock %}

{% block title %} Movimentação de Patrimônio {% endblock %}

{% block breadcrumb %}<!--estrutura de links, paginas anteriores-->
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:index' %}">Patrimônio</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:moviment' %}">Movimentações</a></li>
    <li class="breadcrumb-item active">Detalhes da Movimentação</li>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="moviment-tab" data-toggle="tab" href="#moviment" role="tab" aria-controls="home" aria-selected="true">Movimentação</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="moviment" role="tabpanel" aria-labelledby="moviment-tab">
                <h5 class="card-title">Solicitação [N° - {{ moviment.pk }}]
                    <span class="badge badge-{{ moviment|get_status_css_class }}">{{ moviment.get_status_display }}</span>
                    &raquo;&nbsp;Última atualização - {{ moviment.modified|date:"d/m/Y H:i" }}
                </h5>

                <p class="card-text">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-4"><label class="font-weight-bold">Usuário Responsavel:&nbsp;</label>{{ moviment.user }}</div>
                                <div class="col-md-4"><label class="font-weight-bold">Destino:&nbsp;</label>{{ moviment.destiny }}</div>
                                <div class="col-md-4"><label class="font-weight-bold">Cadastrado em:&nbsp;</label>{{ moviment.created|date:"d/m/Y" }}</div>
                            </div>
                        </li>
                        {% if moviment.status != 1 %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-6"><label class="font-weight-bold">Autorizado por:&nbsp;</label>{{ moviment.authorized_by.username }}</div>
                                <div class="col-md-6"><label class="font-weight-bold">Autorizado em:&nbsp;</label>{{ moviment.authorized_date }}</div>
                            </div>                            
                        </li>
                        {% endif %}
                        <li class="list-group-item">
                            <label class="font-weight-bold">Observação:</label>
                            <p style="text-align: justify;">{{ moviment.obs }}</p>
                        </li>
                    </ul>
                </p>
                {% if moviment.status == 1 %}
                <form class="form-inline js-search-tombo-moviment" action="{% url 'patrimony:search_tombo' moviment.pk %}" method="GET">
                    {% include 'includes/form.html' %}
                    <button class="btn btn-primary ml-4 my-sm-0" type="submit">Buscar</button>
                </form>
                {% endif %}
                <div class="container my-3">
                    <div class="row">
                        {% if moviment.status == 1 %}
                        <div class="col" style="overflow: auto; height:250px">
                            <table class="table table-striped table-sm" id="tombo-table-disponible">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Tombo</th>
                                        <th>Tipo</th>
                                        <th>Marca</th>
                                        <th>Localização</th>
                                        <th>Conservação</th>
                                        <th>Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% include 'patrimony/tombo/search_tombo_moviment.html' %}
                                </tbody>
                            </table>
                        </div>
                        {% endif %} 
                        <div class="col" style="overflow: auto; height:250px">
                            <table class="table table-striped table-sm" id="tombo-table-add">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Tombo</th>
                                        <th>Tipo</th>
                                        <th>Marca</th>
                                        <th>Localização</th>
                                        <th>Conservação</th>
                                        {% if moviment.status != 3 %}
                                        <th>Ações</th>
                                        {% endif %}
                                    </tr>
                                </thead>
                                <tbody>
                                    {% include "patrimony/tombo/add_tombo_moviment.html" %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--Status aberto-->
                {% if moviment.status == 1 and perms.patrimony.can_authorize_moviment %}
                    <a class="btn btn-warning btn-xs" href="{% url 'patrimony:authorize' moviment.pk %}">Autorizar</a>
                {% elif moviment.status == 2 and perms.patrimony.can_authorize_moviment %}
                    <a class="btn btn-success btn-xs" href="{% url 'patrimony:finish' moviment.pk %}">Finalizar</a>
                {% endif %}
                
                {% if moviment.status == 1 %}
                    <button type="button" class="btn btn-primary my-2 js-update-moviment" data-url="{% url 'patrimony:moviment_update' moviment.pk %}">
                        Editar
                    </button>
                {% endif %}
            
                {% if moviment.status|in_list:'1,2' %}
                    <button type="button" class="btn btn-danger my-2 js-delete-moviment" data-url="{% url 'patrimony:moviment_delete' moviment.pk %}">
                        Excluir
                    </button>
                {% endif%}

                {% if moviment.status == 3 %}
                    <a class="btn btn-success btn-xs" href="{% url 'patrimony:responsibility' moviment.pk %}" target="_blank">Termo de Responsabilidade</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!--Modal-->
<div class="modal fade" id="modal">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
</div>

{% endblock %}

patrimony/templates/patrimony/moviment/moviment_list.html
{% extends 'base.html' %}

{% block app_search_form %}<!--Campo de pesquisar-->
    {% include 'includes/search_moviment.html' %}
{% endblock %}

{% load moviment_extras %}

{% block breadcrumb %}<!--estrutura de links, paginas anteriores-->
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:index' %}">Patrimônio</a></li>
    <li class="breadcrumb-item active">Movimentações</li>
{% endblock %}

{% block content %}
    <meta http-equiv="refresh" content="5">
    <div class="my-4"><!--Botão para requisitar nova movimentação-->
        <a class="btn btn-primary" href="{% url 'patrimony:moviment_create' %}">Nova Movimentação</a>
    </div>
    <!--Tabela do patrimonio-->
    <table class="table table-striped table-responsive-sm">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Usuário Responsavel</th>
                <th>Destino</th>
                <th>Criado em</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for moviment in moviments %}
                <tr>
                    <td><a href="{% url 'patrimony:moviment_detail' moviment.pk %}">[Solicitação Nº - {{ moviment.pk }}]</a></td>
                    <td>{{ moviment.user }}</td>
                    <td>{{ moviment.destiny }}</td>
                    <td>{{ moviment.created|date:"d/m/Y" }}</td>
                    <td><span class="badge badge-{{ moviment|get_status_css_class }}">{{ moviment.get_status_display }}</span></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5" class="text-center">Nenhuma Movimentação</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% include 'includes/pagination.html' %}
{% endblock %}

patrimony/templates/patrimony/moviment/moviment_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'patrimony:moviment_update' form.instance.pk %}" class="js-moviment-update-form">
    {% csrf_token %}
    <div class="modal-header">
      <h4 class="modal-title">Atualizar Movimentação</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      {% include 'includes/form.html' %}
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      <button type="submit" class="btn btn-primary">Atualizar</button>
    </div>
</form>

patrimony/templates/patrimony/moviment/responsibility.html
{% load static %}
<!doctype html>
<html>

<head>
    <title>TDR-[Solicitação N° {{ moviment.pk }}]</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>

    <div class="container" style="text-align:center; display: flex; justify-content: center">
        <div class="row">
            <ul class="list-group list-group-flush">
                <div class="text-muted">Solicitação [N° - {{ moviment.pk }}]
                    Gerado por:</label>&nbsp;{{ request.user }} | 
                    Gerado em:</label>&nbsp;{{ date|date:"d/m/y H:i" }}
                </div>
                <li class="list-group-item">
                    <h3>TERMO DE RESPONSABILIDADE</h3>
                    <h6 class="text-muted">DIVISÃO DE MATERIAL PATRIMÔNIO, SERVIÇOS GERAIS E TRANSPORTES - DMPSGT</h6>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-6">
                            <label class="font-weight-bold">Úsuario Responsavel:</label>&nbsp;{{ moviment.user }}
                        </div>
                        <div class="col-md-6">
                            <label class="font-weight-bold">Destino:</label>&nbsp;{{ moviment.destiny }}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <p style="text-align: justify;"><label class="font-weight-bold">Observação:</label>
                    {{ moviment.obs }}</p>
                </li>
                <li class="list-group-item">
                    <h5 class="my-2">Tombos para Movimentação</h5>
                    <table class="table table-bordered table-responsive-sm my-2" id="tombo-table-add">
                        <thead class="thead-light">
                            <tr>
                                <th>Tombo</th>
                                <th>Tipo</th>
                                <th>Marca</th>
                                <th>Descrição</th>
                                <th>Localização</th>
                                <th>Estado de Conservação</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tombo in tombos %}
                                <tr>
                                    <td>{% if tombo.tombo.tombo is not None %}
                                            {{ tombo.tombo.tombo }}
                                        {% else %}
                                            S/T
                                        {% endif %}
                                    </td>
                                    <td>{{ tombo.tombo.equipment_type }}</td>
                                    <td>{{ tombo.tombo.name }}</td>
                                    <td><p style="width:250px;
                                                text-overflow:ellipsis;
                                                white-space:normal;
                                                overflow:hidden">
                                        {{ tombo.tombo.description }}
                                    </p></td>
                                    <td>{{ tombo.previous_location }}</td>
                                    <td>{{ tombo.get_new_conservation_display }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </li>
                <li class="list-group-item">
                    Declaro para os devidos fins de direito, que recebi os Bens acima especificados, para Uso, Guarda e Conservação.
                </li>
                <li class="list-group-item">
                    <table class="table table-condesed table-responsive-sm my-2">
                        <thead class="thead-light">
                            <th>Emitente: Setor de Patrimônio</th>
                            <th>Recebedor</th>
                        </thead>
                        <tbody>
                            <td>
                                <div>Data: ____/____/______</div><br/>
                                <div style="text-align:center">
                                    _________________________________________
                                    <br/>Ass. do Responsável
                                </div>
                            </td>
                            <td>
                                <div>Data: ____/____/______</div><br/>
                                <div style="text-align:center">
                                    _________________________________________
                                    <br/>Ass. do chefe do setor
                                </div>
                            </td>
                        </tbody>
                    </table>
                </li>
            </ul>
        </div>
    </div>
</body>

<script>
    window.print();
</script>

</html>