patrimony/urls.py
from django.conf.urls import url

from . import views
from .views import homePatrimony

urlpatterns = [
    url(r'^$', homePatrimony, name='index'),#pagina inicial de patrimônio

#urls de equipamentos
    url(r'^equipment/$', views.EquipmentList.as_view(), name='equipment'),#lista de equipamentos
    url(r'^equipment/create$', views.equipment_create, name='register_equipment'),#cadastrar equipamento
    url(r'^equipment/(?P<pk>\d+)/detail/$', views.DetailEquipmentView.as_view(), name='detail_equipment'),#detalhar equipamento
    url(r'^equipment/(?P<pk>\d+)/delete/$', views.equipment_delete, name='equipment_delete'),#deletar equipamento
    url(r'^equipment/(?P<pk>\d+)/update/$', views.equipment_update, name='equipment_update'),#atualizar equipamento
    url(r'^equipment/(?P<pk>\d+)/responsibility$', views.equipment_responsibility, name='equipment_responsibility'),#Termo de Responsabilidade para novos objetos
    url(r'^equipment/(?P<pk>\d+)/detail/tombo_history$', views.tombo_history, name='tombo_history'),#histórico de tombo

#urls de movimentações
    url(r'^moviment/$', views.MovimentList.as_view(), name='moviment'),#lista de movimentações
    url(r'^moviment/create$', views.moviment_create, name='moviment_create'),#requisitar movimentações
    url(r'^moviment/search$', views.SearchMoviment.as_view(), name='moviment_search'),#Pesquisar por movimentações
    url(r'^moviment/(?P<pk>\d+)/detail/$', views.moviment_detail, name='moviment_detail'),#detalhar movimentação
    url(r'^moviment/(?P<pk>\d+)/update/$', views.moviment_update, name='moviment_update'),#atualizar movimentação
    url(r'^moviment/(?P<pk>\d+)/delete/$', views.moviment_delete, name='moviment_delete'),#deletar movimentação

#urls tombos na movimentação
    url(r'^moviment/create/search_tombo(?P<pk>\d+)$', views.search_tombo_moviment, name='search_tombo'),#Pesquisar tombos para movimentação
    url(r'^moviment/(?P<pk_m>\d+)/detail/add_tombo(?P<pk_t>\d+)$', views.add_tombo_moviment, name='add_tombo'),#adicionar tombos a movimentação
    url(r'^moviment/(?P<pk_m>\d+)/detail/del_tombo(?P<pk_t>\d+)$', views.del_tombo_moviment, name='del_tombo'),#adicionar tombos a movimentação

#urls autorizar movimentações
    url(r'^moviment/(?P<pk>\d+)/authorize$', views.authorize, name='authorize'),#Autorizar movimentação
    url(r'^moviment/(?P<pk>\d+)/finish$', views.finish, name='finish'),#Finalizar movimentação
    url(r'^moviment/(?P<pk>\d+)/responsibility$', views.responsibility, name='responsibility'),#Termo de Responsabilidade da movimentação
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import home

urlpatterns = [

    url(r'^$', home, name='home'),

    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password/change/$',auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    url(r'^password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),

    url(r'^helpdesk/', include('helpdesk.urls', namespace='helpdesk')),

    url(r'^vehicle_request/', include('vehicle_request.urls', namespace='vehicle_request')),

    url(r'^patrimony/', include('patrimony.urls', namespace="patrimony")),
    
    url(r'^admin/', admin.site.urls),
]

patrimony/models.py
from django.db import models
from django.contrib.auth import get_user_model
from organization.models import Unit
from django.db.models import Q

# Create your models here.
User = get_user_model()

class State(models.Model):
    CONSERVATION_STATE = (
            (0, 'Novo'),
            (1, 'Bom'),
            (2, 'Ruim'),
            (3, 'Inservível')
        )

#########################
#Tipo de Bem Patrimonial
#########################
class EquipmentType(models.Model):
    equipment_type = models.CharField(verbose_name='tipo de bem patrimonial', max_length=100, unique=True)

    def clean(self):
        self.equipment_type = self.equipment_type.capitalize()

    def __str__(self):
        return self.equipment_type
    
    class Meta:
        permissions = (("can_access_patrimony", "pode acessar patrimonio"),
            ("can_authorize_moviment", "pode autorizar movimentacoes"),)

##########################
#Bem Patrimonial
##########################
######QuerySet######
class EquipmentQuerySet(models.query.QuerySet):
    def search(self, query):
        lookups = (
            Q(location__name__icontains=query)
        )
        return self.filter(lookups).distinct()

######Manager######
class EquipmentManager(models.Manager):
    def get_queryset(self):
        return EquipmentQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)
########Equipment##########
class Equipment(models.Model):

    equipment_type = models.ForeignKey(
        EquipmentType, related_name='equipamento', on_delete=models.SET_NULL, null=True)
    name = models.CharField('bem patrimonial', max_length=150)
    tombo = models.PositiveSmallIntegerField(null=True, blank=True, default=True)
    location = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True)
    conservation = models.IntegerField('estado de conservação', choices=State.CONSERVATION_STATE, null=False)
    description = models.TextField('descrição')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    active = models.BooleanField('ativo', default=True)

    objects = EquipmentManager()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name

###################################
#Movimentação de Patrimonio
###################################
######QuerySet######
class MovimentRequestQuerySet(models.query.QuerySet):
    def user(self, request):
        return self.filter(user=request.user)
    
    def search(self, query):
        lookups = (
            Q(pk__icontains=query) |
            Q(user__username__icontains=query) |
            Q(destiny__name__icontains=query)
        )
        return self.filter(lookups).distinct()
    
    def units(self, query):
        lookups = (
            Q(unit__pk__in=query)
        )
        return self.filter(lookups).distinct()

######Manager######
class MovimentRequestManager(models.Manager):
    def get_queryset(self):
        return MovimentRequestQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)

class MovimentRequest(models.Model):
    OPEN_STATUS = 1
    AUTHORIZED_STATUS = 2
    CLOSED_STATUS = 3

    STATUS_CHOICES = (
        (OPEN_STATUS, 'Aberto / Não Autorizado'),
        (AUTHORIZED_STATUS, 'Autorizado'),
        (CLOSED_STATUS, 'Transferido'),
    )
    user = models.ForeignKey(
        User, related_name='moviment_request', on_delete=models.SET_NULL, null=True)
    destiny = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True)
    authorized_by = models.ForeignKey(
        User, related_name='authorized_request', on_delete=models.SET_NULL, null=True)
    authorized_date = models.DateTimeField(blank=True, null=True)
    created = models .DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=OPEN_STATUS)
    obs = models.TextField(blank=True, null=True)

    objects = MovimentRequestManager()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.destiny

# ##########################################
# #Tombos na movimentações
# ##########################################
# #################
# #QuerySet
# #################
class TombosAddQuerySet(models.query.QuerySet):

    def search(self, query):
        lookups = (
            Q(tombo__icontains=query)
        )
        return self.filter(lookups).distinct()

# ################
# #Manager
# ################
class TombosAddManager(models.Manager):

    def get_queryset(self):
        return TombosAddQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)

class TombosAddMoviment(models.Model):

    moviment = models.ForeignKey(MovimentRequest, on_delete=models.SET_NULL, null=True)
    tombo = models.ForeignKey(Equipment, on_delete=models.SET_NULL, null=True)
    new_location = models.CharField(max_length=250, null=True, blank=True)
    previous_location = models.CharField(max_length=250, null=True, blank=True)
    date_moviment = models.DateTimeField(null=True)
    previous_conservation = models.IntegerField(choices=State.CONSERVATION_STATE, null=True)
    new_conservation = models.IntegerField(choices=State.CONSERVATION_STATE, null=False)


    objects = TombosAddManager()

    def __int__(self):
        return self.tombo

patrimony/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models

#######Form para tipo de equipamento############
class TypeEquipmentForm(forms.ModelForm):
    class Meta:
        model = models.EquipmentType
        fields = ['equipment_type']
        labels = {
            'equipment_type': ('Tipo de Bem Patrimonial'),
        }

######Form para equipamentos#################
class EquipmentForm(forms.ModelForm):
    class Meta:
        model = models.Equipment
        fields = ['equipment_type', 'name', 'tombo', 'location', 'conservation', 'description']
        labels = {
            'equipment_type':'Tipo de Bem Patrimonial',
            'name':'Marca do Bem Patrimonial',
            'tombo':'Tombo',
            'location':'Localização',
            'conservation':'Estado de Conservação',
            'description':'Descrição',
        }

        widgets = {'description': forms.Textarea(attrs={'rows': '3'})}

class EquipmentEditForm(forms.ModelForm):
    class Meta:
        model = models.Equipment
        fields = ['equipment_type', 'name', 'description']
        labels = {
            'equipment_type':'Tipo de Bem Patrimonial',
            'name':'Marca do Bem Patrimonial',
            'description':'Descrição',
        }

        widgets = {'description': forms.Textarea(attrs={'rows':'3'})}

#######Form para movimentação de patrimônio#########
class MovimentRequestForm(forms.ModelForm):
    class Meta:
        model = models.MovimentRequest
        fields = ['destiny', 'obs']
        
        labels = {
            'destiny': ('Destino'),
            'obs': ('Observação'),
        }

        widgets = { 'obs': forms.Textarea(attrs={'rows': '3'}), }

class SearchTombosForm(forms.ModelForm):
    # location = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Localização'}))
    class Meta:
        model = models.Equipment
        fields = ['equipment_type', 'location']
        labels = {'equipment_type':'Tipo', 'location':'Localização'}
        # widgets = {'model': forms.TextInput(attrs={'mr': '3'}),}
    def __init__(self, *args, **kwargs):
        super(SearchTombosForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = False

class AddTombosForm(forms.ModelForm):
    class Meta:
        model = models.TombosAddMoviment
        fields = ['moviment', 'tombo']

patrimony/templates/patrimony/equipment/equipment_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'patrimony:register_equipment' %}" class="js-equipment-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Cadastrar Novo Bem Patrimonial</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'includes/form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary">Cadastrar</button>
  </div>
</form>

patrimony/templates/patrimony/equipment/equipment_delete.html
{% load widget_tweaks %}

<form method="post" action="{% url 'patrimony:equipment_delete' equipment.pk %}" class="js-equipment-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Deletar Bem Patrimonial</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Você tem certeza que deseja deletar o bem patrimonial <strong>{{ equipment.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-danger">Excluir</button>
  </div>
</form>

patrimony/templates/patrimony/equipment/equipment_detail.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}
  <script src="{% static 'patrimony/js/equipments.js' %}"></script>
  <script src="{% static 'patrimony/js/tombos.js' %}"></script>
{% endblock %}

{% block title %}Cadastrar Equipamento{% endblock %}

{% block breadcrumb %}<!--estrutura de links, paginas anteriores-->
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:index' %}">Patrimônio</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:equipment' %}">Bens Patrimoniais</a></li>
    <li class="breadcrumb-item active">Detalhes do Bem Patrimonial</li>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="equipment-tab" data-toggle="tab" role="tab"
                    aria-controls="home" aria-selected="true">Bem Patrimonial</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="equipment" role="tabpanel" aria-labelledby="equipment-tab">
                <h5 class="card-title">Bem Patrimonial [N° - {{ equipment.pk }}]
                    {% if equipment.active == 1 %}
                        <span class="badge badge-success">Ativo</span>
                    {% endif %}
                    {% if equipment.active == 0 %}
                        <span class="badge badge-danger">Inativo</span>
                    {% endif %}
                    &raquo; Tombo - {% if equipment.tombo is None %}
                                        Sem Tombo
                                    {% else %} 
                                        {{ equipment.tombo }}
                                    {% endif %}
                </h5>
                {% if equipment.conservation == 0 %}
                    <a class="btn btn-success btn-xs" href="{% url 'patrimony:equipment_responsibility' equipment.pk %}" target="_blank">
                        Termo de Responsabilidade
                    </a>
                {% endif %}
                
                <p class="card-text">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-6"><label class="font-weight-bold">Tipo do Bem Patrimonial:&nbsp;</label>{{ equipment.model }}</div>
                                <div class="col-md-6"><label class="font-weight-bold">Marca do Bem Patrimonial:&nbsp;</label>{{ equipment.name }}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row"> 
                                <div class="col-md-6"><label class="font-weight-bold">Localização:&nbsp;</label>{{ equipment.location }}</div>
                                <div class="col-md-6"><label class="font-weight-bold">Estado de Conservação:&nbsp;</label>{{ equipment.get_conservation_display }}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-6"><label class="font-weight-bold">Cadastrado em:&nbsp;</label>{{ equipment.created }}</div>
                                <div class="col-md-6"><label class="font-weight-bold">Última atualização:&nbsp;</label>{{ equipment.modified }}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <label class="font-weight-bold">Descrição:</label>
                            <p style="text-align: justify;">{{ equipment.description }}</p>
                        </li>
                    </ul>
                </p>
                <a class="btn btn-warning"
                    href="{% url 'patrimony:tombo_history' equipment.pk %}" target="_blank">
                    Histórico
                </a>
                <button type="button" class="btn btn-primary my-2 js-update-equipment" data-url="{% url 'patrimony:equipment_update' equipment.pk %}">
                    Editar
                </button>
                <button type="button" class="btn btn-danger my-2 js-delete-equipment" data-url="{% url 'patrimony:equipment_delete' equipment.pk %}">
                    Excluir
                </button>
            </div>
        </div>
    </div>
</div>

<!--Modal-->
<div class="modal fade" id="modal">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
</div>

{% endblock %}

patrimony/templates/patrimony/equipment/equipment_list.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}
  <script src="{% static 'patrimony/js/equipments.js' %}"></script>
{% endblock %}

{% block breadcrumb %}<!--estrutura de links, paginas anteriores-->
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'patrimony:index' %}">Patrimônio</a></li>
    <li class="breadcrumb-item active">Bens Patrimoniais</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-7"> <!--Botão para cadastrar novo equipamento-->
        <button type="button" class="btn btn-primary my-2 js-create-equipment"
        data-url="{% url 'patrimony:register_equipment' %}">
            Novo Bem Patrimonial
        </button>
    </div>
    
    <form class="form-inline" action="{% url 'patrimony:equipment' %}" method="GET">
        {% include 'includes/form.html' with form=search_tombo %}
        <button class="btn btn-success" type="submit">Buscar</button>
    </form>
    
</div>

    <!--Tabela do patrimonio-->
    <table class="table table-striped table-responsive-sm" id="equipment-table">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Tombo</th>
                <th>Tipo</th>
                <th>Marca</th>
                <th>Localização</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for equipment in equipments %}
                <tr>
                    <td><a href="{% url 'patrimony:detail_equipment' equipment.id %}">[Nº - {{ equipment.pk }}]</a></td>
                    <td>
                        {% if equipment.tombo is None %}
                            S/T
                        {% else %}
                            {{ equipment.tombo }}
                        {% endif %}
                    </td>
                    <td>{{ equipment.equipment_type }}</td>
                    <td>{{ equipment.name }}</td>
                    <td>{{ equipment.location }}</td>
                    {% if equipment.active == 1 %}
                        <td><span class="badge badge-success">Ativo</span></td>
                    {% endif %}
                    {% if equipment.active == 0 %}
                        <td><span class="badge badge-danger">Inativo</span></td>
                    {% endif %}
                </tr>
                {% empty %}
                <tr>
                    <td colspan="8" class="text-center">Nenhum Bem Patrimonial</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
<!--Modal-->
    <div class="modal fade" id="modal">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>

{% include 'includes/pagination.html' %}
{% endblock %}

patrimony/templates/patrimony/equipment/equipment_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'patrimony:equipment_update' form.instance.pk %}" class="js-equipment-update-form">
    {% csrf_token %}
    <div class="modal-header">
      <h4 class="modal-title">Atualizar Bem Patrimonial</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      {% include 'includes/form.html' %}
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      <button type="submit" class="btn btn-primary">Atualizar</button>
    </div>
</form>

patrimony/templates/patrimony/equipment/responsibility.html
{% load static %}
<!doctype html>
<html>

<head>
    <title>TDR-[Bem Patrimonial N° {{ equipment.pk }}]</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>

    <div class="container" style="text-align:center; display: flex; justify-content: center">
        <div class="row">
            <ul class="list-group list-group-flush">
                <div class="text-muted">Patrimônio [N° - {{ equipment.pk }}] | 
                    Gerado por:</label>&nbsp;{{ request.user }} | 
                    Gerado em:</label>&nbsp;{{ date|date:"d/m/y H:i" }}
                </div>
                <li class="list-group-item">
                    <h3>TERMO DE RESPONSABILIDADE</h3>
                    <h6 class="text-muted">DIVISÃO DE MATERIAL PATRIMÔNIO, SERVIÇOS GERAIS E TRANSPORTES - DMPSGT</h6>
                </li>
                <li class="list-group-item">
                    <table class="table table-bordered table-sm my-2">
                        <thead class="thead-light">
                            <tr>
                                <th style="width:10%">Tombo</th>
                                <th style="width:10%">Tipo</th>
                                <th style="width:10%">Marca</th>
                                <th style="width:50%">Descrição</th>
                                <th style="width:10%">Localização</th>
                                <th style="width:10%">Conservação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{% if equipment.tombo is not None %}
                                        {{ equipment.tombo }}
                                    {% else %}
                                        S/T
                                    {% endif %}
                                </td>
                                <td>{{ equipment.equipment_type }}</td>
                                <td>{{ equipment.name }}</td>
                                <td>
                                    {{ equipment.description }}
                                </td>
                                <td>{{ equipment.location }}</td>
                                <td>{{ equipment.get_conservation_display }}</td>
                            </tr>
                        </tbody>
                    </table>
                </li>
                <li class="list-group-item">
                    Declaro para os devidos fins de direito, que recebi os Bens acima especificados, para Uso, Guarda e Conservação.
                </li>
                <li class="list-group-item">
                    <table class="table table-condesed table-responsive-sm my-2">
                        <thead class="thead-light">
                            <th>Chefe de Divisão</th>
                        </thead>
                        <tbody>
                            <td>
                                <div>Data: ____/____/______</div><br/>
                                <div style="text-align:center">
                                    _________________________________________
                                    <br/>Ass. do Responsável
                                </div>
                            </td>
                        </tbody>
                    </table>
                </li>
            </ul>
        </div>
    </div>
</body>

<script>
    window.print();
</script>

</html>