helpdesk/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^ticket/create$', views.CreateTicket.as_view(), name='create'),
    url(r'^ticket/(?P<pk>\d+)/detail$', views.TicketDetail.as_view(), name='detail'),
    url(r'^ticket/(?P<pk>\d+)/followup$', views.add_follow_up, name='followup'),
    url(r'^ticket/(?P<pk>\d+)/update$', views.TicketUpdate.as_view(), name='update'),
    url(r'^ticket/(?P<pk>\d+)/delete$', views.TicketDelete.as_view(), name='delete'),
    url(r'^ticket/(?P<pk>\d+)/pdf$', views.TicketPDF.as_view(), name='pdf'),
    url(r'^ticket/(?P<pk>\d+)/assing$', views.assign_to, name='assign'),

    url(r'^search/$', views.SearchTicketView.as_view(), name='search'),
    url('^ajax/load-rankings/$', views.load_rankings, name='ajax_load_rankings'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import home

urlpatterns = [

    url(r'^$', home, name='home'),

    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password/change/$',auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    url(r'^password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),

    url(r'^helpdesk/', include('helpdesk.urls', namespace='helpdesk')),

    url(r'^vehicle_request/', include('vehicle_request.urls', namespace='vehicle_request')),

    url(r'^patrimony/', include('patrimony.urls', namespace="patrimony")),
    
    url(r'^admin/', admin.site.urls),
]

helpdesk/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q

# Create your models here.
User = get_user_model()

class Ranking(models.Model):
    """
    Classificacao do chamado
    """

    DEVELOPMENT = 'DE'
    INFRASTRUCTURE = 'IN'
    BUSINESS = 'BN'
    SUPPORT = 'SU'

    IT_QUEUE = (
        (DEVELOPMENT, 'Desenvolvimento'),
        (INFRASTRUCTURE, 'Infraestrutura'),
        (BUSINESS, 'Negócios'),
        (SUPPORT, 'Suporte'),
    )

    name            = models.CharField(max_length=50)
    queue           = models.CharField(max_length=2, choices=IT_QUEUE)
    sla_to_analyze  = models.PositiveSmallIntegerField(blank=True)
    sla_to_solve    = models.PositiveSmallIntegerField(blank=True)

    def __str__(self):
        return self.name


class TicketQuerySet(models.query.QuerySet):

    def user(self, request):
        return self.filter(user=request.user)

    def search(self, query):
        lookups = (
            Q(user__username__icontains=query) |
            Q(pk__icontains=query) |
            Q(ranking__name__icontains=query)
        )
        return self.filter(lookups).distinct()


class TicketManager(models.Manager):

    def get_queryset(self):
        return TicketQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class Ticket(models.Model):
    """
    Ticket do chamado
    """

    OPEN_STATUS = 1
    RESOLVED_STATUS = 2
    CLOSED_STATUS = 3
    REOPENED_STATUS = 4

    STATUS_CHOICES = (
        (OPEN_STATUS, 'Aberto'),
        (RESOLVED_STATUS, 'Solucionado'),
        (CLOSED_STATUS, 'Encerrado'),
        (REOPENED_STATUS, 'Reaberto'),
    )

    PRIORITY_CHOICES = (
        (1, '1 - Alto'),
        (2, '2 - Médio'),
        (3, '3 - Normal'),
        (4, '4 - Baixo'),
    )

    user        = models.ForeignKey(User, related_name='tickets', on_delete=models.SET_NULL, null=True)
    assigned_to = models.ForeignKey(User, related_name='assigned_to', on_delete=models.SET_NULL, null=True)
    ranking     = models.ForeignKey(Ranking, on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    status      = models.IntegerField(choices=STATUS_CHOICES, default=OPEN_STATUS)
    priority    = models.IntegerField(choices=PRIORITY_CHOICES, default=3)
    created     = models.DateTimeField(auto_now_add=True)
    modified    = models.DateTimeField(auto_now=True)

    objects = TicketManager()

    class Meta:

        ordering = ['-created']

    def __str__(self):
        return self.description


class FollowUp(models.Model):

    ticket  = models.ForeignKey(Ticket, related_name='followups', on_delete=models.CASCADE)
    user    = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status  = models.IntegerField(choices=Ticket.STATUS_CHOICES, blank=True)

    def __str__(self):
        return self.comment

helpdesk/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models


class ClientForm(forms.ModelForm):

    class Meta:

        model = models.Ticket
        fields = ['description']
        exclude = ['user', 'priority', 'ranking', ]
        labels = {
            'description': ('Descrição'),
        }


class StaffForm(forms.ModelForm):
    
    queue = forms.ChoiceField(label="Fila", choices=models.Ranking.IT_QUEUE)
    
    class Meta:

        model = models.Ticket
        
        fields = ['user', 'priority', 'queue', 'ranking', 'description']
        
        labels = {
            'description': ('Descrição'),
            'user': ('Usuário'),
            'priority': ('Prioridade'),
            'ranking': ('Requisição'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = User.objects.filter(is_active=True).order_by('username')       
        self.fields['ranking'].queryset = models.Ranking.objects.none()

        if 'queue' in self.data:
            try:
                queue = self.data.get('queue')
                self.fields['ranking'].queryset = models.Ranking.objects.filter(queue=queue).order_by('name')
            except (ValueError, TypeError):
                pass
        #elif self.instance.pk:#ao atualizar
        #    self.fields['ranking'].queryset = models.Ranking.objects.filter(queue=self.instance.ranking.queue).order_by('name')

    
class TicketUpdateForm(forms.ModelForm):

    queue = forms.ChoiceField(label="Fila", choices=models.Ranking.IT_QUEUE)
    
    class Meta:

        model = models.Ticket
        fields = ['priority', 'queue', 'ranking']
        labels = {
            'priority': ('Prioridade'),
            'ranking': ('Requisição'),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ranking'].queryset = models.Ranking.objects.none()

        if 'queue' in self.data:#ao submeter
            try:
                queue = self.data.get('queue')
                self.fields['ranking'].queryset = models.Ranking.objects.filter(queue=queue).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:#ao atualizar
            if self.instance.ranking is not None:
                self.fields['ranking'].queryset = models.Ranking.objects.filter(queue=self.instance.ranking.queue).order_by('name')
            

helpdesk/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import (LoginRequiredMixin,)
from django.contrib.auth.models import Group
from django.contrib import messages

from .models import Ticket, FollowUp, Ranking
from .forms import ClientForm, StaffForm, TicketUpdateForm

# Create your views here.
def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False


class IndexView(LoginRequiredMixin, generic.ListView):

    model = Ticket
    template_name = 'helpdesk/ticket_list.html'
    context_object_name = 'ticket_list'
    paginate_by = 2

    def get_queryset(self, *args, **kwargs):

        if has_group(self.request.user, 'helpdesk_staff'):
            return super().get_queryset().user(self.request)
        else:
            return super().get_queryset(*args, **kwargs)


class CreateTicket(LoginRequiredMixin, generic.CreateView):

    model = Ticket
    success_url = '/helpdesk/'

    def get_form(self, form_class=None):
        form = super(CreateTicket, self).get_form()
        return form

    def get_form_class(self):

        FORMS = {
            "Client": ClientForm,
            "Staff": StaffForm,
        }

        if not has_group(self.request.user, 'helpdesk_staff'):
            return FORMS['Client']
        else:
            return FORMS['Staff']

    def form_valid(self, form):
        self.object = form.save(commit=False)

        if not form.cleaned_data.get('user'):
            self.object.user = self.request.user

        self.object.save()
        return super().form_valid(form)


class TicketDetail(LoginRequiredMixin, generic.DetailView):

    model = Ticket

    def get(self, request, *args, **kwargs):
        obj = self.get_object()

        if has_group(request.user, 'helpdesk_staff') or obj.user == request.user:
            return super(TicketDetail, self).get(request, *args, **kwargs)
        else:
            messages.error(
                request, 'É possível apenas acessar os seus Tickets.')
            return redirect(reverse('tickets:index'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['follow_up_list'] = FollowUp.objects.filter(
            ticket__pk=self.kwargs.get('pk'))
        return context


class TicketUpdate(LoginRequiredMixin, generic.UpdateView):

    model = Ticket
    form_class = TicketUpdateForm
    template_name_suffix = '_update'
    success_url = '/helpdesk/'

    def get(self, request, *args, **kwargs):
        obj = self.get_object()

        if not obj.status in [Ticket.OPEN_STATUS, Ticket.REOPENED_STATUS]:
            messages.warning(request, 'O Ticket não pode ser editado.')
            return redirect(reverse('helpdesk:detail', kwargs={'pk': obj.pk}))

        if not obj.assigned_to == self.request.user:
            messages.warning(
                request, 'Apenas o técnico associado pode atualizar o Ticket.')
            return redirect(reverse('helpdesk:detail', kwargs={'pk': obj.pk}))
        else:
            return super(TicketUpdate, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, 'Ticket atualizdo com sucesso.')
        return super().form_valid(form)


class TicketDelete(LoginRequiredMixin, generic.DeleteView):

    model = Ticket
    template_name_suffix = '_confirm_delete'
    success_url = '/helpdesk/'

    #TODO fazer modal ajax da exclusao

    def delete(self, request, *args, **kwargs):

        obj = super(TicketDelete, self).get_object()

        follow_up_list = FollowUp.objects.filter(ticket__pk=obj.pk)

        if obj.assigned_to == request.user or obj.user == request.user:

            if not follow_up_list:
                messages.success(self.request, 'Ticket excluído.')
                return super(TicketDelete, self).delete(request, *args, **kwargs)
            else:
                messages.error(
                    request, 'Ticket não pode ser excluido pois possui atendimentos associados.')
        else:
            messages.warning(
                request, 'Somente o técnico associado ou o usuário pode excluir o Ticket.')

        return redirect(reverse('helpdesk:detail', kwargs={'pk': obj.pk}))


class TicketPDF(LoginRequiredMixin, generic.View):

    def get(self, request, *args, **kwargs):

        ticket = get_object_or_404(Ticket, pk=self.kwargs['pk'])

        if has_group(request.user, 'helpdesk_staff') or ticket.user == request.user:
            followup = FollowUp.objects.filter(ticket=ticket)
        else:
            messages.error(
                request, 'É possível apenas acessar os seus Tickets.')
            return redirect(reverse('tickets:index'))

        return render(request, 'helpdesk/ticket_pdf.html', {"ticket": ticket, "follow_up_list": followup, })


class SearchTicketView(LoginRequiredMixin, generic.ListView):

    model = Ticket
    context_object_name = 'ticket_list'
    template_name = 'helpdesk/ticket_list.html'

    def get_context_data(self, *args, **kwargs):
    	context = super(SearchTicketView, self).get_context_data(*args, **kwargs)
    	context['query'] = self.request.GET.get('q')
    	return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')

        if query is not None:
            if not has_group(self.request.user, 'helpdesk_staff'):
                return Ticket.objects.search(query).filter(user=self.request.user)
            else:
                return Ticket.objects.search(query)
        return Ticket.objects.none()


def assign_to(request, pk):

    if request.method == 'GET' and has_group(request.user, 'helpdesk_staff'):

        ticket = get_object_or_404(Ticket, pk=pk)

        if ticket.assigned_to == None:
            ticket.assigned_to = request.user
            ticket.save()
            messages.success(request, 'Técnico associado com sucesso.')
        else:
            messages.warning(
                request, 'O Ticket já possui um técnico associado.')

    return redirect(reverse('helpdesk:detail', kwargs={'pk': pk}))


def add_follow_up(request, pk):

    if request.method == 'POST':

        ticket = get_object_or_404(Ticket, pk=pk)

        if ticket.assigned_to == request.user:
            if not ticket.ranking:
                messages.warning(request, 'O ticket precisa ser classificado primeiro.')
            else:
                follow_up = FollowUp(
                    ticket=ticket,
                    user=request.user,
                    comment=request.POST['comment'],
                    status=request.POST['status']
                )
                follow_up.save()

                ticket.status = request.POST['status']
                ticket.save()

                messages.success(request, 'Atendimento cadastrado com sucesso.')
        else:
            messages.warning(
                request, 'Apenas o técnico associado pode adicionar um atendimento.')

    return redirect(reverse('helpdesk:detail', kwargs={'pk': pk}))


def load_rankings(request):
    queue_id = request.GET.get('queue')
    rankings = Ranking.objects.filter(queue=queue_id).order_by('name')
    return render(request, 'helpdesk/ranking_dropdown_list_options.html', {'rankings': rankings})

helpdesk/templates/helpdesk/ticket_detail.html
{% extends 'base.html' %}
{% load ticket_extras %}

{% block title %}Ticket{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'helpdesk:index' %}">Helpdesk</a>
</li>
<li class="breadcrumb-item active">Ticket</li>
{% endblock %}

{% block content %}

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="ticket-tab" data-toggle="tab" href="#ticket" role="tab" aria-controls="home" aria-selected="true">Ticket</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="followup-tab" data-toggle="tab" href="#followup" role="tab" aria-controls="followup" aria-selected="false">Atendimentos</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="ticket" role="tabpanel" aria-labelledby="ticket-tab">
                <h5 class="card-title">Ticket [N° - {{ ticket.pk }}]
                    <span class="badge badge-{{ ticket|get_priority_css_class }}">{{ ticket.get_priority_display }}</span>
                    <span class="badge badge-{{ ticket|get_status_css_class }}">{{ ticket.get_status_display }}</span>
                    Última atualização - {{ ticket.modified|date:"d/m/y H:i" }}
                </h5>
                <a class="btn btn-danger btn-xs" href="{% url 'helpdesk:pdf' ticket.pk %}" target="_blank">PDF</a>
                
                <p class="card-text">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><label class="font-weight-bold">Técnico Associado:&nbsp;</label>
                            {% if ticket.assigned_to %}
                                {{ ticket.assigned_to }}
                            {% else %}
                                {% if user|has_group:"helpdesk_staff" %}
                            <a class="btn btn-warning btn-xs" href="{% url 'helpdesk:assign' ticket.pk %}" role="button">Atribuir</a>
                                {% endif %}
                            {% endif %}
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-6"><label class="font-weight-bold">Aberto por:&nbsp;</label>{{ ticket.user.username }}</div>
                                <div class="col-md-6"><label class="font-weight-bold">Aberto em:&nbsp;</label>{{ ticket.created|date:"d/m/y H:i" }}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-6"><label class="font-weight-bold">Fila:&nbsp;</label>{{ ticket.ranking.get_queue_display }}</div>
                                <div class="col-md-6"><label class="font-weight-bold">Requisição:&nbsp;</label>{{ ticket.ranking.name }}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <label class="font-weight-bold">Descrição:</label>
                            <p style="text-align: justify;">{{ ticket.description }}</p>
                        </li>
                    </ul>
                </p>

                {% if ticket.status|in_list:'1,4' %}
                    {% if user|has_group:"helpdesk_staff"%}
                <a class="btn btn-warning btn-xs" href="{% url 'helpdesk:update' ticket.pk %}">Editar</a>
                    {% endif %}
                    <button type="button" id="modalDeleteButton" class="btn btn-danger" data-toggle="modal" data-target="#modalDelete">
                        Excluir
                    </button>
                {% endif%}
            </div>

            <div class="tab-pane fade" id="followup" role="tabpanel" aria-labelledby="followup-tab">
                {% if user|has_group:"helpdesk_staff" %}
                <form action="{% url 'helpdesk:followup' pk=ticket.pk %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="comment" class="control-label">Comentário / Solução:</label>
                        <textarea class="form-control" rows="5" name="comment" required></textarea>
                    </div>
                    
                    <div class="form-group">
                    
                        <!--Ticket Aberto-->
                        {% ifequal ticket.status 1 %}
                        <label class="radio-inline">
                            <input type='radio' name='status' value='1' checked='checked'>Aberto &raquo;</label>
                        <label class="radio-inline">
                            <input type='radio' name='status' value='2'>Solucionado &raquo;</label>
                        <label class="radio-inline">
                            <input type='radio' name='status' value='3'>Encerrado</label>
                        {% endifequal %}
                    
                        <!--Ticket Solucionado-->
                        {% ifequal ticket.status 2 %}
                        <label class="radio-inline">
                            <input type='radio' name='status' value='4'>Reaberto &laquo;</label>
                        <label class="radio-inline">
                            <input type='radio' name='status' value='2' checked='checked'>Solucionado &raquo;</label>
                        <label class="radio-inline">
                            <input type='radio' name='status' value='3'>Encerrado</label>
                        {% endifequal %}
                    
                        <!--Ticket Encerrado-->
                        {% ifequal ticket.status 3 %}
                        <label class="radio-inline">
                            <input type='radio' name='status' value='4'>Reaberto &laquo;</label>
                        <label class="radio-inline">
                            <input type='radio' name='status' value='3' checked='checked'>Encerrado</label>
                        {% endifequal %}
                    
                        <!--Ticket Reaberto-->
                        {% ifequal ticket.status 4 %}
                        <label class="radio-inline">
                            <input type='radio' name='status' value='4' checked='checked'>Reaberto &laquo;</label>
                        <label class="radio-inline">
                            <input type='radio' name='status' value='2'>Solucionado &raquo;</label>
                        <label class="radio-inline">
                            <input type='radio' name='status' value='3'>Encerrado</label>
                        {% endifequal %}
                    
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </form>
                {% endif %}

                <p class="card-text">
                    <ul class="list-group list-group-flush">   
                        {% for follow_up in follow_up_list reversed %}
                        <li class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">Atendimento</h5>
                                <small>{{ follow_up.created|date:"d/m/y H:i" }}</small>
                            </div>
                            <p class="mb-1">{{ follow_up.comment }}</p>
                            <label class="font-weight-bold">Status:&nbsp;</label><span class="badge badge-{{ follow_up|get_status_css_class }}">{{ follow_up.get_status_display }}</span>
                        </li>
                        {% endfor %}                                            
                    </ul>
                </p>
            </div>
        </div>
    </div>

</div>

<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDelete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmar Exclusão?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente excluir o registro?
            </div>
            <div class="modal-footer">
                <form action="{% url 'helpdesk:delete' ticket.pk %}" method="post">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

helpdesk/templates/helpdesk/ticket_form.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block title %}Novo Ticket{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'helpdesk:index' %}">Helpdesk</a></li>
<li class="breadcrumb-item active">Novo Ticket</li>
{% endblock %}

{% block content %}
<form method="post" id="ticketForm" data-rankings-url="{% url 'helpdesk:ajax_load_rankings' %}" novalidate>
  {% csrf_token %}
  
  {% include 'includes/form.html' %}

  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function () {
        $("#id_queue").change(function () {
            var url = $("#ticketForm").attr("data-rankings-url");  // get the url of the `load_cities` view
            var queueId = $(this).val();                           // get the selected country ID from the HTML input
            $.ajax({                                               // initialize an AJAX request
                url: url,                                          // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                    'queue': queueId                               // add the country id to the GET parameters
                },
                success: function (data) {                         // `data` is the return of the `load_cities` view function
                    $("#id_ranking").html(data);                   // replace the contents of the city input with the data that came from the server
                }
            });

        });
    });    
</script> 
{% endblock %}

helpdesk/templates/helpdesk/ticket_list.html
{% extends 'base.html' %}

{% block app_search_form %}
    {% include 'includes/helpdesk_search_form.html' %}
{% endblock %}

{% load ticket_extras %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
  <li class="breadcrumb-item active">Helpdesk</li>
{% endblock %}

{% block content %}

<div class="my-4">
    <a class="btn btn-primary" href="{% url 'helpdesk:create' %}">Novo ticket</a>
</div>

<table class="table table-striped table-responsive-sm">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Usuário</th>
            <th>Requisição</th>
            <th>Prioridade</th>
            <th>Status</th>
            <th>Criado em</th>
        </tr>
    </thead>
    <tbody>
        {% for ticket in ticket_list %} 
        <tr>
            <td><a href="{% url 'helpdesk:detail' ticket.id %}">[Ticket N° - {{ ticket.id }}]</a></td>
            <td>{{ ticket.user.username }}</td>
            <td>{% if ticket.ranking %}{{ ticket.ranking }}{% else %}Sem classificação{% endif %}</td>
            <td><span class="badge badge-{{ ticket|get_priority_css_class }}">{{ ticket.get_priority_display }}</span></td>
            <td><span class="badge badge-{{ ticket|get_status_css_class }}">{{ ticket.get_status_display }}</span></td>
            <td>{{ ticket.created|date:"d/m/y H:i" }}</td>
        </tr>
        {% endfor %}                
    </tbody>
</table>

{% include 'includes/pagination.html' %}

{% endblock %}

helpdesk/templates/helpdesk/ticket_pdf.html
{% load static %}
<!doctype html>
<html>

<head>
    <title>[Ticket N° {{ ticket.pk }}]</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>

    <div class="container">

        <table class="table table-condensed">
            <tbody>
                <tr>
                    <th>Aberto por:</th>
                    <td>{{ ticket.user }}</td>
                    <th>Status:</th>
                    <td>{{ ticket.get_status_display }}</td>
                </tr>
                <tr>
                    <th>Localidade:</th>
                    <td></td>
                    <th>Setor:</th>
                    <td></td>
                </tr>
                <tr>
                    <th>Fila:</th>
                    <td>{{ ticket.ranking.get_queue_display }}</td>
                    <th>Requisição:</th>
                    <td>{{ ticket.ranking.name }}</td>
                </tr>
                <tr>
                    <th>SLA - Análise:</th>
                    <td>{{ ticket.ranking.sla_to_analyze }}</td>
                    <th>SLA - Solução:</th>
                    <td>{{ ticket.ranking.sla_to_solve }}</td>
                </tr>
                <tr>
                    <th>Técnico Associado:</th>
                    <td colspan="3">{{ ticket.assigned_to }}</td>
                </tr>
                <tr>
                    <th>Aberto em:</th>
                    <td>{{ ticket.created|date:"d/m/y H:i" }}</td>
                    <th>Ultima Atualização:</th>
                    <td>{{ ticket.modified|date:"d/m/y H:i" }}</td>
                </tr>
                <tr>
                    <th>Descrição:</th>
                    <td colspan="3">{{ ticket.description }}</td>
                </tr>
            </tbody>
        </table>

        <hr/>

        <h2>Atendimentos</h2>
        <ul class="list-group list-group-flush">
            {% for follow_up in follow_up_list reversed %}
            <li class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Atendimento</h5>
                    <small>{{ follow_up.created|date:"d/m/y H:i" }}</small>
                </div>
                <p class="mb-1">{{ follow_up.comment }}</p>
                <label class="font-weight-bold">Status:&nbsp;</label>{{ follow_up.get_status_display }}
            </li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>

helpdesk/templates/helpdesk/ticket_update.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block title %}Create Ticket{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">SIAGED</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'helpdesk:index' %}">Helpdesk</a>
</li>
<li class="breadcrumb-item active">Atualizar Ticket</li>
{% endblock %} 

{% block content %}
<form method="post" id="ticketForm" data-rankings-url="{% url 'helpdesk:ajax_load_rankings' %}" novalidate>
  {% csrf_token %} 
  
  {% include 'includes/form.html' %}

  <button type="submit" class="btn btn-success">Atualizar</button>
</form>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function () {
        $("#id_queue").change(function () {
            var url = $("#ticketForm").attr("data-rankings-url");  // get the url of the `load_cities` view
            var queueId = $(this).val();                           // get the selected country ID from the HTML input
            $.ajax({                                               // initialize an AJAX request
                url: url,                                          // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                    'queue': queueId                               // add the country id to the GET parameters
                },
                success: function (data) {                         // `data` is the return of the `load_cities` view function
                    $("#id_ranking").html(data);                   // replace the contents of the city input with the data that came from the server
                }
            });

        });
    });    
</script> 
{% endblock %}